default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 1 } %>

development:
  <<: *default
  database: surf_spot_community_development

test:
  <<: *default
  database: surf_spot_community_test

production:
  <<: *default
  database: surf_spot_community_production
  username: surf_spot_community
  password: <%= ENV["FOTO_LOG_DATABASE_PASSWORD"] %>
